image:https://m-m-m.github.io/logo.svg[logo,width="150",link="https://m-m-m.github.io"]

image:https://img.shields.io/github/license/m-m-m/marshall.svg?label=License["Apache License, Version 2.0",link=https://github.com/m-m-m/marshall/blob/master/LICENSE]
image:https://travis-ci.com/m-m-m/marshall.svg?branch=master["build-status",link="https://travis-ci.com/m-m-m/marshall"]

== mmm-marshall

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-marshall.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://m-m-m.github.io/javadoc.svg?status=online["apidoc",link="https://m-m-m.github.io/docs/api/io.github.mmm.marshall/module-summary.html"]

The module `io.github.mmm.marshall` (artifactId `mmm-marshall`) provides the API to marshall (serialize) and unmarshall (deserialize) data from/to structured formats such as JSON or XML.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-marshall</artifactId>
</dependency>
```

Module Dependency:
```java
  requires transitive io.github.mmm.marshall;
```

== mmm-marshall-jsonp

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-marshall-jsonp.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://m-m-m.github.io/javadoc.svg?status=online["apidoc",link="https://m-m-m.github.io/docs/api/io.github.mmm.marshall.jsonp/module-summary.html"]

The module `io.github.mmm.marshall.jsonp` (artifactId `mmm-marshall-jsonp`) provides the implementation to marshall (serialize) and unmarshall (deserialize) data from/to JSON via JSON-P.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-marshall-jsonp</artifactId>
</dependency>
```

Module Dependency:
```java
  requires static io.github.mmm.marshall.jsonp;
```

== mmm-marshall-stax

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-marshall-stax.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://m-m-m.github.io/javadoc.svg?status=online["apidoc",link="https://m-m-m.github.io/docs/api/io.github.mmm.marshall.stax/module-summary.html"]

The module `io.github.mmm.marshall.stax` (artifactId `mmm-marshall-stax`) provides the implementation to marshall (serialize) and unmarshall (deserialize) data from/to XML via StAX (Streaming API for XML).

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-marshall-stax</artifactId>
</dependency>
```

Module Dependency:
```java
  requires static io.github.mmm.marshall.stax;
```
