image:https://m-m-m.github.io/logo.svg[logo,width="150",link="https://m-m-m.github.io"]

image:https://img.shields.io/github/license/m-m-m/marshall.svg?label=License["Apache License, Version 2.0",link=https://github.com/m-m-m/marshall/blob/master/LICENSE]
image:https://github.com/m-m-m/marshall/actions/workflows/build.yml/badge.svg["Build Status",link="https://github.com/m-m-m/marshall/actions/workflows/build.yml"]

== mmm-marshall

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-marshall.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-marshall/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-marshall]

The module `io.github.mmm.marshall` (artifactId `mmm-marshall`) provides the API to marshall (serialize) and unmarshall (deserialize) data from/to structured formats such as JSON, XML, YAML, or even ProtoBuf (gRPC) without implementing your mapping code for multiple formats. 

== Problem

When you want to do (un)marshalling with Java EE standards the current state is:

* https://javaee.github.io/jsonp/[JSON-P] to map to/from https://www.json.org/[JSON].
* https://javaee.github.io/jaxb-v2/[JAXB] to map to/from https://en.wikipedia.org/wiki/XML[XML].
* no support for other formats like https://yaml.org/[YAML], https://grpc.io/[gRPC], https://developers.google.com/protocol-buffers/[ProtoBuf], etc.

As a result you implement your marshalling and unmarshalling code for a single format. If you want to support a different format, you have to start from scratch.
Further, the reference implementation for https://javaee.github.io/jsonp/[JSON-P] is lacking obvious features. E.g. the indentation is hardcoded as you can see 
https://github.com/eclipse-ee4j/jsonp/blob/dcef07f088197eb7f44829a3ccf4f6a9b99d29ff/impl/src/main/java/org/glassfish/json/JsonPrettyGeneratorImpl.java#L31[here].
You can also not configure to include or omit `null` values. Also, there is no build in support to skip a value and doing so requires an awful lot of code (in case the value might contain nested arrays and/or objects).

== Solution

So instead we define a universal API for (un)marshalling. You can write your mapping code once and then you can benefit from all formats supported by this project or even add custom formats as plugin yourself.

== Features

* Simple but powerful API to marshall and unmarshall your data in a format agnostic way.
* link:core/src/main/java/io/github/mmm/marshall/MarshallingConfig.java#L21[Configurable indendation]
* link:core/src/main/java/io/github/mmm/marshall/MarshallingConfig.java#L28[Configuration to omit null values]
* Works in JVM as well as in the browser using http://teavm.org/[TeaVM] or as cloud-native binary using https://www.graalvm.org/[GraalVM].
* You can even use https://github.com/m-m-m/bean[mmm-bean] to get the entire marshalling and unmarshalling for free with many other cool features.
* You can furhter use https://github.com/m-m-m/rpc[mmm-rpc] to implement client and/or server for https://en.wikipedia.org/wiki/Remote_procedure_call[RCP] communication with minimum code but maximum benefits (support for different formats, sync/async/reactive support, etc.).

We provide the following implementations:

** link:impl/json/README.adoc[mmm-marshall-json] (native implementation for JSON with flexibilty)
** link:impl/jsonp/README.adoc[mmm-marhsall-jsonp] (implementation for JSON based on JSON-P)
** link:impl/stax/README.adoc[mmm-marshall-stax] (implementation for XML based on StAX)
** link:impl/tvm-xml/README.adoc[mmm-marshall-tvm-xml] (implementation for XML using TeaVM and XML API of the browser)
** link:impl/protobuf/README.adoc[mmm-marshall-protobuf] (implementation for ProtoBuf/gRPC)
** link:impl/yaml/README.adoc[mmm-marshall-yaml] (implementation for YAML with flexibility)
** link:impl/snakeyaml/README.adoc[mmm-marshall-snakeyaml (implementation for YAML based on SnakeYaml)

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-marshall</artifactId>
  <!-- <version>${mmmVersion}</version> -->
</dependency>
```
Gradle Dependency:
```
implementation 'io.github.m-m-m:mmm-marshall:${mmmVersion}'
```
For `${mmmVersion}` please fill in the latest version that you can find in the badge above.

Module Dependency:
```java
  requires transitive io.github.mmm.marshall;
```

== Example

To get started we use a very simple example based on a stupid POJO that every vanilla Java developer will immediately understand.
Please note that we provide much better beans with build-in marshalling support via https://github.com/m-m-m/bean[mmm-bean].
However, here comes our stupid example:

```java
public class Person {
  private String name;
  private int age;
  public String getName() { return this.name; }
  public void setName(String name) { this.name = name; }
  public int getAge() { return this.age; }
  public void setAge(int age) { this.age = age; }
}
```

Now, we can marshall a `Person` like this:
```java
public void marshall(StructuredWriter writer, Person person) {
  writer.writeStartObject();
  writer.writeName("name", 1);
  writer.writeValue(person.getName());
  writer.writeName("age", 2);
  writer.writeValue(person.getAge());
  writer.writeEnd();
}
```

Now we run the following code:
```java
Person person = new Person();
person.setName("John Doe");
person.satAge(42);
StringBuilder sb = new StringBuilder();
StructuredWriter writer = JsonFormat.of().writer(sb);
marshall(writer, person);
System.out.println(sb.toString());
```

This will print the following output:
```json
{
  "name": "John Doe",
  "age": 42
}
```

The interesting fact is that you can exchange `JsonFormat.of()` with something else to get a different format without changing your implementation of `marshal`. So you can also use `XmlFormat.of()` to produce XML or you can generate YAML or even gRPC/ProtoBuf.

To unmarhall a `Person` you can do something like this:

```java
public void unmarshall(StructuredReader reader, Person person) {
  while (!reader.readEnd()) {
    if (reader.isName("name", 1)) {
      person.setName(reader.readValueAsString());
    } else if (reader.isName("age", 2)) {
      person.setAge(reader.readValueAsInteger());
    } else {
      // ignore unknown property for compatibility
      // we have dynamic properties support in mmm-bean
      // even much better than gRPC generated unknownFields
    }
  }
}
```
